version: "3.8"
services:
  ### MYSQL Database ####
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_PASSWORD: fundall-assessment
      MYSQL_ROOT_PASSWORD: fundall-assessment
      MYSQL_USER: fundall-assessment
      MYSQL_DATABASE: fundall_assessment
      MYSQL_TCP_PORT: 3307
    restart: always
  #    volumes:
  #      - mysql_db_data:/var/lib/mysql

  ### MySQL Adminer ####
  adminer:
    container_name: adminer_container
    image: adminer
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    ports:
      - "8080:8080"
    restart: always

  ### API Spring Boot ####
  server:
    container_name: fundall-assessment
    image: teem001/fundall-assessment
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/fundall_assessment?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.driver
    ports:
      - "8083:8083"
    restart: always
